const DB_NAME = 'HRN_LOCAL_DB', DB_VERSION = 2;
const hazards = {
  'Mecánico': ['Aplastamiento / Contacto intempestivo','Atrapamiento / Bloqueo de acceso','Caída de objetos de manipulación','Desniveles / Superficies resbaladizas / Obstáculos','Elementos punzantes / cortantes / enganche / abrasión','Interacción con equipos móviles','Proyección de partículas','Trabajo en altura'],
  'Eléctrico': ['Descarga eléctrica'], 'Térmico': ['Alta temp.','Baja temp.','Material incandescente'],
  'Presión': ['Tuberías con presión y conexiones','Fluidos a presión: proyección','Tanques a presión'],
  'Radiación': ['Gamma','IRojo','Ultra V','X'], 'Sustancias peligrosas': ['Biológicas','Explosivos','Gases y humos','Líquidos'],
  'Del ambiente': ['Baja luminosidad','Calor / Frío','Hum. excesiva / insuficiente','Intemperie','Ruido'],
  'Ergonómico': ['Espacios confinados','Hiperextensión','Mov. antinaturales','Mov. repetitivos','Vibraciones'],
  'De información': ['Conexionados','Documentación','Señalización y dispositivos de alarma'],
  'De funcionamiento': ['Accionamientos / Pulsadores','Paradas de emergencia','Puesta en marcha intempestiva']
};
const DPH=[['0.1','Rasguño / Moretón'],['0.5','Quemadura / Corte / Enfermedad corto plazo'],['1','Rotura menor de hueso de dedo, mano o pie'],['2','Rotura mayor de hueso de dedo, mano o pie'],['4','Pérdida de 1 o 2 dedos'],['8','Amputación pierna / mano. Pérdida auditiva o visual parcial'],['15','Muerte']];
const LO=[['0.03','Imposible. No puede pasar bajo ninguna circunstancia'],['0.1','Casi improbable. Sólo es posible bajo circunstancias extremas.'],['0.5','Es muy improbable. Aunque concebible'],['1','Improbable. Pero podría ocurrir'],['2','Posible. Pero inusual'],['5','Hay posibilidades. Puede pasar'],['8','Probable. No sorpresivo'],['10','Probablemente. Se puede esperar que ocurra'],['15','Cierto. Indudable']];
const FE=[['0.1','Infrecuentemente'],['0.2','Anualmente'],['1','Mensualmente'],['1.5','Semanalmente'],['2.5','Diario'],['4','Por hora'],['5','En cada ciclo. Constante']];
const NP=[['1','De 1 a 2'],['2','De 3 a 7'],['4','De 8 a 15'],['8','De 16 a 50'],['12','Más de 50']];
let db, state={client:null,machine:null,zone:null,assessment:null,photos:[]};
const stores=['clients','machines','zones','assessments','photos','settings'];
const $=s=>document.querySelector(s), uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random().toString(16).slice(2);
function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=()=>{db=r.result;for(const s of stores)if(!db.objectStoreNames.contains(s))db.createObjectStore(s,{keyPath:'id'});};r.onsuccess=()=>{db=r.result;resolve(db)};r.onerror=()=>reject(r.error)})}
function tx(s,m='readonly'){return db.transaction(s,m).objectStore(s)}
function put(s,o){return new Promise((a,b)=>{const r=tx(s,'readwrite').put(o);r.onsuccess=()=>a(o);r.onerror=()=>b(r.error)})}
function del(s,id){return new Promise((a,b)=>{const r=tx(s,'readwrite').delete(id);r.onsuccess=()=>a();r.onerror=()=>b(r.error)})}
function all(s){return new Promise((a,b)=>{const r=tx(s).getAll();r.onsuccess=()=>a(r.result);r.onerror=()=>b(r.error)})}
function get(s,id){return new Promise((a,b)=>{const r=tx(s).get(id);r.onsuccess=()=>a(r.result);r.onerror=()=>b(r.error)})}
function setView(n){document.querySelectorAll('.view').forEach(v=>v.classList.add('hidden'));$('#view'+n).classList.remove('hidden')}
function breadcrumb(){const a=['Clientes'];if(state.client)a.push(state.client.name);if(state.machine)a.push(state.machine.name);if(state.zone)a.push(state.zone.name);$('#breadcrumbs').textContent=a.join(' › ')}
function card(h){return `<article class="card">${h}</article>`}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function num(n){return Number.isInteger(Number(n))?String(n):Number(n).toFixed(2).replace(/0+$/,'').replace(/\.$/,'')}
function sanitizePath(s){return String(s||'').replace(/[\\/\?%\*:|"<>]/g,'_').trim()||'Sin_nombre'}
function isoDate(v){return (v||'').slice(0,10)}
function alphaSort(xs,key){return xs.slice().sort((a,b)=>String(a?.[key]??'').localeCompare(String(b?.[key]??''),'es',{sensitivity:'base',numeric:true}));}


async function renderClients(){state={client:null,machine:null,zone:null,assessment:null,photos:[]};breadcrumb();setView('Clients');const xs=alphaSort(await all('clients'),'name');$('#clientsList').innerHTML=xs.length?xs.map(c=>card(`<span class="tag">${esc(c.industry)}</span><h3>${esc(c.name)}</h3><p>Planta: ${esc(c.plant)}</p><p>Proyecto: ${esc(isoDate(c.projectCreatedAt||c.createdAt))}</p><div class="card-actions"><button onclick="selectClient('${c.id}')">Abrir</button><button class="secondary" onclick="editClient('${c.id}')">Editar</button><button class="secondary" onclick="removeItem('clients','${c.id}')">Eliminar</button></div>`)).join(''):`<div class="empty">No hay clientes cargados.</div>`;updateCounts()}
async function renderMachines(){breadcrumb();setView('Machines');$('#machinesTitle').textContent=`Máquinas / líneas — ${state.client.name}`;const xs=alphaSort((await all('machines')).filter(x=>x.clientId===state.client.id),'name');$('#machinesList').innerHTML=xs.length?xs.map(m=>card(`<h3>${esc(m.name)}</h3><p>${esc(m.description||'')}</p><div class="card-actions"><button onclick="selectMachine('${m.id}')">Abrir</button><button class="secondary" onclick="editMachine('${m.id}')">Editar</button><button class="secondary" onclick="removeItem('machines','${m.id}')">Eliminar</button></div>`)).join(''):`<div class="empty">No hay máquinas o líneas cargadas.</div>`}
async function renderZones(){breadcrumb();setView('Zones');$('#zonesTitle').textContent=`Zonas — ${state.machine.name}`;const xs=alphaSort((await all('zones')).filter(x=>x.machineId===state.machine.id),'name');$('#zonesList').innerHTML=xs.length?xs.map(z=>card(`<h3>${esc(z.name)}</h3><p>${esc(z.description||'')}</p><div class="card-actions"><button onclick="selectZone('${z.id}')">Abrir</button><button class="secondary" onclick="editZone('${z.id}')">Editar</button><button class="secondary" onclick="removeItem('zones','${z.id}')">Eliminar</button></div>`)).join(''):`<div class="empty">No hay límites espaciales cargados.</div>`}
async function renderAssessments(){breadcrumb();setView('Assessments');$('#assessmentsTitle').textContent=`Peligros y riesgos — ${state.zone.name}`;const xs=(await all('assessments')).filter(x=>x.zoneId===state.zone.id);$('#assessmentsList').innerHTML=xs.length?xs.map(a=>card(`<span class="tag">${esc(a.hazardType)}</span><h3>${esc(a.risk)}</h3><div class="risk-card"><div class="hrn">HRN ${num(a.hrn)}</div></div><p>Fotos: ${a.photoCount||0} · Guardado local</p><div class="card-actions"><button onclick="editAssessment('${a.id}')">Abrir / Editar</button><button class="secondary" onclick="removeAssessment('${a.id}')">Eliminar</button></div>`)).join(''):`<div class="empty">No hay análisis para esta zona.</div>`;updateCounts()}
function fillSelect(el,arr){el.innerHTML=arr.map(x=>`<option value="${x[0]}">${x[0]} — ${esc(x[1])}</option>`).join('')}
function setupAssessmentForm(a={}){$('#hazardType').innerHTML=Object.keys(hazards).map(x=>`<option>${esc(x)}</option>`).join('');fillSelect($('#dph'),DPH);fillSelect($('#lo'),LO);fillSelect($('#fe'),FE);fillSelect($('#np'),NP);$('#hazardType').value=a.hazardType||Object.keys(hazards)[0];populateRisks(a.risk);$('#dph').value=a.dph??'0.1';$('#lo').value=a.lo??'0.03';$('#fe').value=a.fe??'0.1';$('#np').value=a.np??'1';$('#notes').value=a.notes||'';$('#assessmentId').value=a.id||'';state.photos=[];calcHRN();renderPhotos()}
function populateRisks(sel){const h=$('#hazardType').value;$('#risk').innerHTML=hazards[h].map(x=>`<option>${esc(x)}</option>`).join('');if(sel)$('#risk').value=sel}
async function renderPhotos(){const f=state.assessment?(await all('photos')).filter(p=>p.assessmentId===state.assessment.id):state.photos;$('#photoGrid').innerHTML=f.map(p=>`<div class="photo"><img src="${p.dataUrl}" alt="Evidencia"><button type="button" onclick="removePhoto('${p.id}')">×</button></div>`).join('')}
function calcHRN(){const v=['#dph','#lo','#fe','#np'].map(s=>Number($(s).value||0));$('#hrnValue').textContent=num(v.reduce((a,b)=>a*b,1))}
function openClientForm(c={}){$('#clientName').value=c.name||'';$('#industryType').value=c.industry||'';$('#plantName').value=c.plant||'';$('#projectDate').value=c.projectCreatedAt?isoDate(c.projectCreatedAt):new Date().toISOString().slice(0,10);$('#clientDialog').dataset.editId=c.id||'';$('#projectDate').disabled=!!c.id;$('#clientDialog').showModal()}
function openMachineForm(m={}){$('#machineName').value=m.name||'';$('#machineDescription').value=m.description||'';$('#machineDialog').dataset.editId=m.id||'';$('#machineDialog').showModal()}
function openZoneForm(z={}){$('#zoneName').value=z.name||'';$('#zoneDescription').value=z.description||'';$('#zoneDialog').dataset.editId=z.id||'';$('#zoneDialog').showModal()}

window.selectClient=async id=>{state.client=await get('clients',id);state.machine=null;state.zone=null;renderMachines()};window.selectMachine=async id=>{state.machine=await get('machines',id);state.zone=null;renderZones()};window.selectZone=async id=>{state.zone=await get('zones',id);renderAssessments()};window.editClient=async id=>openClientForm(await get('clients',id));window.editMachine=async id=>openMachineForm(await get('machines',id));window.editZone=async id=>openZoneForm(await get('zones',id));window.editAssessment=async id=>{const a=await get('assessments',id);state.assessment=a;setView('Assessment');breadcrumb();$('#assessmentTitle').textContent='Editar análisis HRN';setupAssessmentForm(a)};
window.removeItem=async(s,id)=>{if(!confirm('¿Eliminar registro?'))return;await del(s,id);if(s==='clients'){for(const m of (await all('machines')).filter(x=>x.clientId===id)){for(const z of (await all('zones')).filter(x=>x.machineId===m.id)){for(const a of (await all('assessments')).filter(x=>x.zoneId===z.id)){for(const p of (await all('photos')).filter(x=>x.assessmentId===a.id))await del('photos',p.id);await del('assessments',a.id)}await del('zones',z.id)}await del('machines',m.id)}await renderClients()}else if(s==='machines')await renderMachines();else await renderZones();await updateCounts()};
window.removeAssessment=async id=>{if(!confirm('¿Eliminar análisis y sus fotos?'))return;for(const p of (await all('photos')).filter(p=>p.assessmentId===id))await del('photos',p.id);await del('assessments',id);await renderAssessments();if(state.client)await syncProjectToDisk(state.client.id)};window.removePhoto=async id=>{await del('photos',id);await renderPhotos();if(state.assessment)await syncProjectToDisk(state.client.id)};

$('#newClientBtn').onclick=()=>openClientForm();
$('#clientForm').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,dialog=$('#clientDialog'),btn=form.querySelector('button[value="default"]');try{btn.disabled=true;btn.textContent='Guardando…';const id=dialog.dataset.editId||uid(),existing=await get('clients',id),name=$('#clientName').value.trim(),industry=$('#industryType').value.trim(),plant=$('#plantName').value.trim(),projectDate=$('#projectDate').value;if(!name||!industry||!plant||!projectDate){alert('Complete todos los campos del proyecto.');return}const c={id,name,industry,plant,createdAt:existing?.createdAt||new Date().toISOString(),projectCreatedAt:existing?.projectCreatedAt||projectDate,updatedAt:new Date().toISOString()};await put('clients',c);dialog.close();form.reset();dialog.dataset.editId='';$('#projectDate').disabled=false;state.client=c;await ensureProjectFolders(c);await renderClients()}catch(err){console.error(err);alert('No se pudo guardar el proyecto localmente.\n\n'+(err?.message||err))}finally{btn.disabled=false;btn.textContent='Guardar'}};
$('#newMachineBtn').onclick=()=>openMachineForm();$('#machineForm').onsubmit=async e=>{e.preventDefault();const id=$('#machineDialog').dataset.editId||uid(),m={id,clientId:state.client.id,name:$('#machineName').value.trim(),description:$('#machineDescription').value.trim(),updatedAt:new Date().toISOString()};if(!m.name){alert('Indique el nombre de la máquina o línea.');return}await put('machines',m);$('#machineDialog').close();e.target.reset();$('#machineDialog').dataset.editId='';await renderMachines();await syncProjectToDisk(state.client.id)};
$('#newZoneBtn').onclick=()=>openZoneForm();$('#zoneForm').onsubmit=async e=>{e.preventDefault();const id=$('#zoneDialog').dataset.editId||uid(),z={id,machineId:state.machine.id,name:$('#zoneName').value.trim(),description:$('#zoneDescription').value.trim(),updatedAt:new Date().toISOString()};if(!z.name){alert('Indique el nombre de la zona.');return}await put('zones',z);$('#zoneDialog').close();e.target.reset();$('#zoneDialog').dataset.editId='';await renderZones();await syncProjectToDisk(state.client.id)};
$('#newAssessmentBtn').onclick=()=>{state.assessment=null;setView('Assessment');breadcrumb();$('#assessmentTitle').textContent='Nuevo análisis HRN';setupAssessmentForm()};$('#cancelAssessmentBtn').onclick=()=>renderAssessments();$('#backAssessmentBtn').onclick=()=>renderAssessments();$('#backAssessmentsBtn').onclick=()=>renderZones();$('#backZonesBtn').onclick=()=>renderMachines();$('#backMachinesBtn').onclick=()=>renderClients();$('#hazardType').onchange=()=>populateRisks();['#dph','#lo','#fe','#np'].forEach(s=>$(s).onchange=calcHRN);
$('#photoInput').onchange=async e=>{try{for(const file of [...e.target.files]){const dataUrl=await resizeImage(file,1600);const p={id:uid(),assessmentId:$('#assessmentId').value||'draft',dataUrl,name:file.name,mime:file.type||'image/jpeg',createdAt:new Date().toISOString()};state.photos.push(p);await put('photos',p)}await renderPhotos()}catch(err){alert('No se pudo guardar la evidencia.\n\n'+err.message)}finally{e.target.value=''}};
function resizeImage(file,max){return new Promise((resolve,reject)=>{const r=new FileReader();r.onerror=()=>reject(r.error);r.onload=()=>{const img=new Image();img.onerror=()=>reject(new Error('No se pudo leer la imagen.'));img.onload=()=>{const scale=Math.min(1,max/img.width),c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);resolve(c.toDataURL('image/jpeg',.82))};img.src=r.result};r.readAsDataURL(file)})}
$('#assessmentForm').onsubmit=async e=>{e.preventDefault();const btn=e.currentTarget.querySelector('button[type="submit"]');try{btn.disabled=true;btn.textContent='Guardando…';const id=$('#assessmentId').value||uid();for(const p of state.photos.filter(p=>p.assessmentId==='draft')){p.assessmentId=id;await put('photos',p)}const a={id,zoneId:state.zone.id,hazardType:$('#hazardType').value,risk:$('#risk').value,dph:Number($('#dph').value),lo:Number($('#lo').value),fe:Number($('#fe').value),np:Number($('#np').value),hrn:Number($('#hrnValue').textContent),notes:$('#notes').value.trim(),photoCount:(await all('photos')).filter(p=>p.assessmentId===id).length,updatedAt:new Date().toISOString()};await put('assessments',a);state.assessment=a;state.photos=[];await syncProjectToDisk(state.client.id);await renderAssessments()}catch(err){console.error(err);alert('No se pudo guardar el análisis.\n\n'+(err?.message||err))}finally{btn.disabled=false;btn.textContent='Guardar análisis'}};

async function projectData(){const [clients,machines,zones,assessments,photos]=await Promise.all(stores.slice(0,5).map(all));return{version:6,exportedAt:new Date().toISOString(),clients,machines,zones,assessments,photos}}
function csvExport(data){const rows=[['Cliente','Industria','Planta','Fecha proyecto','Máquina/Línea','Zona','Tipo de peligro','Riesgo','DPH','LO','FE','NP','HRN','Observaciones','Fotos','Actualizado']];const cs=Object.fromEntries(data.clients.map(x=>[x.id,x])),ms=Object.fromEntries(data.machines.map(x=>[x.id,x])),zs=Object.fromEntries(data.zones.map(x=>[x.id,x]));for(const a of data.assessments){const z=zs[a.zoneId]||{},m=ms[z.machineId]||{},c=cs[m.clientId]||{};rows.push([c.name,c.industry,c.plant,isoDate(c.projectCreatedAt),m.name,z.name,a.hazardType,a.risk,a.dph,a.lo,a.fe,a.np,a.hrn,a.notes,a.photoCount,a.updatedAt])}return rows.map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(';')).join('\n')}
function downloadBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
$('#exportBtn').onclick=async()=>downloadBlob(new Blob(['\ufeff'+csvExport(await projectData())],{type:'text/csv;charset=utf-8'}),'Relevamiento_HRN.csv');

// ===== Almacenamiento real en el sistema de archivos =====
let rootHandle=null;
const FS_SUPPORTED='showDirectoryPicker' in window;
async function saveRootHandle(handle){rootHandle=handle;await put('settings',{id:'rootHandle',handle,name:handle.name,savedAt:new Date().toISOString()});await updateStorageUI()}
async function loadRootHandle(){try{const s=await get('settings','rootHandle');if(s?.handle)rootHandle=s.handle}catch(e){console.warn('No se pudo recuperar la carpeta 08_APP',e)}}
async function hasWritePermission(handle){if(!handle?.queryPermission)return true;return (await handle.queryPermission({mode:'readwrite'}))==='granted'}
async function requestWritePermission(handle){if(!handle?.requestPermission)return true;return (await handle.requestPermission({mode:'readwrite'}))==='granted'}
async function selectLocalRoot(){if(!FS_SUPPORTED)throw new Error('Este navegador no ofrece acceso directo a carpetas. La APP seguirá funcionando con IndexedDB y exportación de archivos. Para crear carpetas reales use Chrome/Edge en un contexto HTTPS.');const selected=await window.showDirectoryPicker({id:'hrn-08-app',mode:'readwrite',startIn:'documents'});let handle=selected;if(selected.name!=='08_APP'){const ok=confirm(`La carpeta seleccionada es "${selected.name}". ¿Crear dentro de ella una carpeta "08_APP"?`);if(!ok)return false;handle=await selected.getDirectoryHandle('08_APP',{create:true})}if(!(await requestWritePermission(handle)))throw new Error('No se otorgó permiso de escritura para 08_APP.');await saveRootHandle(handle);return true}
async function ensureRoot(){if(!rootHandle)await loadRootHandle();if(!rootHandle)throw new Error('Primero configure la carpeta 08_APP.');if(!(await hasWritePermission(rootHandle)) && !(await requestWritePermission(rootHandle)))throw new Error('No hay permiso de escritura sobre 08_APP.');return rootHandle}
async function getDir(parent,name){return parent.getDirectoryHandle(sanitizePath(name),{create:true})}
async function getFile(dir,name,content,type='text/plain'){const fh=await dir.getFileHandle(sanitizePath(name),{create:true});const w=await fh.createWritable();await w.write(typeof content==='string'?new Blob([content],{type}):content);await w.close();return fh}
async function projectFolder(client){const root=await ensureRoot();const folder=await getDir(root,`${sanitizePath(client.name)}_${isoDate(client.projectCreatedAt||client.createdAt)}`);return folder}
async function ensureProjectFolders(client){if(!rootHandle)return false;const pf=await projectFolder(client);await getDir(pf,'00_Datos_Proyecto');await getDir(pf,'01_Evidencias');await getDir(pf,'02_Datos_Relevados');await syncProjectToDisk(client.id);return true}
function dataUrlToBlob(dataUrl){const [head,b64]=dataUrl.split(',');const mime=(head.match(/data:([^;]+)/)||[])[1]||'image/jpeg';const bin=atob(b64),bytes=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)bytes[i]=bin.charCodeAt(i);return new Blob([bytes],{type:mime})}
async function writeAssessmentToDisk(client,machine,zone,assessment,photos){const pf=await projectFolder(client),evRoot=await getDir(pf,'01_Evidencias'),dataRoot=await getDir(pf,'02_Datos_Relevados');const machineEv=await getDir(evRoot,machine.name),zoneEv=await getDir(machineEv,zone.name),riskFolder=await getDir(zoneEv,`${assessment.risk}_${assessment.id}`);const machineData=await getDir(dataRoot,machine.name),zoneData=await getDir(machineData,zone.name);const payload={project:client,machine,zone,assessment,photos:photos.map(p=>({id:p.id,name:p.name,mime:p.mime,createdAt:p.createdAt}))};await getFile(zoneData,`${assessment.risk}_${assessment.id}.json`,JSON.stringify(payload,null,2),'application/json');for(const p of photos)await getFile(riskFolder,p.name||`evidencia_${p.id}.jpg`,dataUrlToBlob(p.dataUrl),p.mime||'image/jpeg')}
async function syncProjectToDisk(clientId){if(!rootHandle)return false;const data=await projectData(),client=data.clients.find(c=>c.id===clientId);if(!client)return false;const pf=await projectFolder(client),dataDir=await getDir(pf,'00_Datos_Proyecto'),projectMachines=data.machines.filter(m=>m.clientId===client.id),projectMachineIds=new Set(projectMachines.map(m=>m.id)),projectZones=data.zones.filter(z=>projectMachineIds.has(z.machineId)),zoneIds=new Set(projectZones.map(z=>z.id)),projectAssessments=data.assessments.filter(a=>zoneIds.has(a.zoneId)),projectPhotos=data.photos.filter(p=>projectAssessments.some(a=>a.id===p.assessmentId));const payload={version:6,project:client,machines:projectMachines,zones:projectZones,assessments:projectAssessments,photoCount:projectPhotos.length,exportedAt:new Date().toISOString()};await getFile(dataDir,'proyecto.json',JSON.stringify(payload,null,2),'application/json');await getFile(dataDir,'Relevamiento_HRN.csv','\ufeff'+csvExport({clients:[client],machines:projectMachines,zones:projectZones,assessments:projectAssessments,photos:projectPhotos}),'text/csv;charset=utf-8');const byId=Object.fromEntries(projectMachines.map(m=>[m.id,m]));const zonesById=Object.fromEntries(projectZones.map(z=>[z.id,z]));for(const a of projectAssessments){const z=zonesById[a.zoneId],m=byId[z.machineId],ps=projectPhotos.filter(p=>p.assessmentId===a.id);await writeAssessmentToDisk(client,m,z,a,ps)}await updateStorageUI();return true}

async function updateStorageUI(){const configured=!!rootHandle;$('#storageStatus').textContent=configured?`08_APP: ${rootHandle.name}`:'08_APP: no configurado';$('#storageFooter').textContent=configured?`Carpeta: ${rootHandle.name}`:'Carpeta: no configurada';$('#storageStatus').classList.toggle('storage-ok',configured)}
$('#storageBtn').onclick=()=>{$('#storageInfo').innerHTML=FS_SUPPORTED?'<p>Seleccione la carpeta <strong>08_APP</strong>. Si selecciona su carpeta padre, la APP puede crear 08_APP dentro de ella.</p>':'<p>Este navegador no permite manipular carpetas reales. Se usará almacenamiento local del navegador.</p>';$('#storageDialog').showModal()};$('#closeStorageBtn').onclick=()=>$('#storageDialog').close();$('#pickStorageBtn').onclick=async()=>{try{$('#pickStorageBtn').disabled=true;const ok=await selectLocalRoot();if(ok){$('#storageInfo').innerHTML='<p class="ok">✔ Carpeta 08_APP configurada correctamente.</p>';if(state.client)await syncProjectToDisk(state.client.id)}}catch(e){$('#storageInfo').innerHTML=`<p class="err">${esc(e.message||e)}</p>`}finally{$('#pickStorageBtn').disabled=false}};
async function updateCounts(){const as=await all('assessments');$('#pendingCount').textContent=`Análisis: ${as.length}`}

window.addEventListener('error',e=>console.error('HRN Local error:',e.error||e.message));window.addEventListener('unhandledrejection',e=>console.error('HRN Local promise error:',e.reason));
let deferredInstall;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;$('#installBtn').classList.remove('hidden')});$('#installBtn').onclick=async()=>{if(deferredInstall){deferredInstall.prompt();deferredInstall=null}};
(async()=>{await openDB();await loadRootHandle();await updateStorageUI();if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').then(r=>r.update().catch(()=>{})).catch(e=>console.warn('Service Worker:',e));await renderClients();await updateCounts()})();
